/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YXIcons {
  YXIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData windows = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData playstation = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData btn_game_DS = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData other = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData NS__ = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData xbox = const IconData(0xebb7, fontFamily: _kFontFam);
}
